### ISSUE TITLE
Error when upgrade to `2.2.0` from `2.1.0`

### ISSUE THREAD

**Issue by kntmrkm** [stevenosloan/slack-notifier#79] opened 2017-05-27 09:51 UTC
```
Bundler::GemRequireError: There was an error while trying to load the gem 'slack-notifier'.
Gem Load Error is: uninitialized constant Slack
Backtrace for gem load error is:
```

just me?

**Comment by dawidof** [comment] 2017-05-27 14:07
Got the same

**Comment by dawidof** [comment] 2017-05-27 14:13
```ruby
/Users/dawidof/.rvm/gems/ruby-2.4.0@global/gems/bundler-1.13.7/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'slack-notifier'.
Gem Load Error is: uninitialized constant Slack
Backtrace for gem load error is:
/Users/dawidof/.rvm/gems/ruby-2.4.0/gems/slack-notifier-2.2.0/lib/slack-notifier/util/http_client.rb:5:in `<top (required)>'
/Users/dawidof/.rvm/gems/ruby-2.4.0/gems/slack-notifier-2.2.0/lib/slack-notifier.rb:5:in `require_relative'
/Users/dawidof/.rvm/gems/ruby-2.4.0/gems/slack-notifier-2.2.0/lib/slack-notifier.rb:5:in `<top (required)>'
```

**Comment by ened** [comment] 2017-05-28 02:04
Quickfix, in your application.rb:

```
module Slack; end
class Slack::Notifier; end
```

before `Bundler.require(*Rails.groups)`.

Root cause might be in https://github.com/stevenosloan/slack-notifier/blob/master/lib/slack-notifier/util/http_client.rb#L5

**Comment by llamicron** [comment] 2017-05-28 05:10
@ened That worked for me. I'm not using rails. You say to declare that before `Bundler.require(*Rails.groups)`, for anyone else using rails, this means before the gem is required. Thanks.

**Comment by renchap** [comment] 2017-05-28 13:14
BTW this is fixed in #78

**Comment by ened** [comment] 2017-05-28 16:05
@renchap @dawidof let's fix it once and for all and starts a CI server

**Comment by dawidof** [comment] 2017-05-28 21:54
@ened how do you want to fix it? PR is already waiting and it looks ok.

**Comment by giedriusr** [comment] 2017-05-29 04:39
How did it happen that the release is broken? No one tested before releasing? Why it is not merged yet.

**Comment by llamicron** [comment] 2017-05-29 05:27
Looks like it hasn't been built and pushed to rubygems.org yet. @stevenosloan when can we expect a push, now that #78 has fixed this issue?

**Comment by pwim** [comment] 2017-05-29 05:53
@giedriusr This is an issue to do with requires, so testing it is tricky. I'm assuming within the context of the specs, because of the order files are required, things work properly. Off hand, I can't think of an easy way to test requiring a gem within a Rails project, and I think most Ruby gems would be susceptible to a similar issue slipping in.

As to why the maintainer has merged it yet, there could be many reasons. Note that this isn't an official slack gem, and the maintainer is just a volunteer. We're not paying @stevenosloan anything, so I don't think we have any right to demand a fixed version is quickly released.

Looking at [the changelog](https://github.com/stevenosloan/slack-notifier/blob/master/changelog.md), the only thing 2.2.0 adds is raising an exception when there is an error. As this functionality was only added to help improve debugging, you can safely downgrade your version of slack notifier. I neat trick I've found is to declare the gem like the following:

``` ruby
gem 'slack-notifier', '!= 2.2.0'
```

This will prevent the bundling of the broken 2.2.0, but automatically pull in any other future version, which will presumably fix this issue.

**Comment by siegy22** [comment] 2017-05-29 07:03
I'm sorry to have introduced this bug in 2.2.0.. I wrote tests to test the new "feature" in #76. They all passed as you can see in the PR. @giedriusr 

@pwim Thanks for the detailed explanation and your nice behaviour.

This will be fixed soon! 💚  (thanks to @pocke for the extrem fast opened PR)

**Comment by stevenosloan** [comment] 2017-05-29 21:49
Hey y'all, just pushed up `2.2.1` with the fix -- apologies for letting that sneak in. I am a little surprised that it didn't get picked up when the specs run on Travis, but it looks like running things with bundle exec manipulates things in such a way it's able to run.

```bash
$ slack-notifier [(HEAD detached at 2.2.0)] Δ bundle exec ruby -e "require 'slack-notifier'; puts Slack::Notifier::VERSION" -I lib
2.2.0

$ slack-notifier [(HEAD detached at 2.2.0)] Δ ruby -e "require 'slack-notifier'; puts Slack::Notifier::VERSION" -I lib
/Volumes/Dev/code/slack-notifier/lib/slack-notifier/util/http_client.rb:5:in `<top (required)>': uninitialized constant Slack (NameError)
```

**Closed by stevenosloan** 2017-05-29 21:49 UTC
